# Generated by Django 4.2.8 on 2023-12-09 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_alter_vendor_address_and_more'),
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='average_response_time',
            field=models.FloatField(default=0.0, help_text='Historical record of the average response time.'),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of the performance record.'),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='fulfillment_rate',
            field=models.FloatField(default=0.0, help_text='Historical record of the fulfilment rate.'),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0.0, help_text='Historical record of the on-time delivery rate.'),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='quality_rating_avg',
            field=models.FloatField(default=0.0, help_text='Historical record of the quality rating average.'),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='acknowledgment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the vendor acknowledged the PO.'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Expected or actual delivery date of the order.'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the PO was issued to the vendor.'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='items',
            field=models.JSONField(help_text='Details of items ordered.'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the order was placed.'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='quality_rating',
            field=models.FloatField(help_text='Rating given to the vendor for this PO (nullable).', null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity of items in the PO.'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], default='PENDING', help_text='Current status of the PO (e.g., pending, completed, canceled).', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='vendor',
            field=models.ForeignKey(help_text='Link to the Vendor model.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor'),
        ),
    ]
